// CarreiraMais — Mock Data

const SKILLS_CATEGORIES = {
  'Tecnologia': [
    'Python','JavaScript','HTML/CSS','Java','SQL','Excel Avançado','Power BI',
    'Git','Linux','Docker','Machine Learning','Inteligência Artificial',
    'Segurança da Informação','Redes de Computadores','UX/UI Design',
    'Figma','React','Node.js','C#','PHP','TypeScript','Go','Rust',
    'Kotlin','Swift','Dart','Ruby','Vue.js','Angular','Flutter',
    'AWS','PostgreSQL','MongoDB','.NET','AutoCAD'
  ],
  'Negócios e Gestão': [
    'Gestão de Projetos','Scrum/Agile','Liderança','Negociação',
    'Atendimento ao Cliente','Gestão Financeira','Empreendedorismo',
    'Marketing Digital','SEO','Copywriting','Análise de Dados',
    'Gestão de Pessoas','Planejamento Estratégico'
  ],
  'Saúde': [
    'Primeiros Socorros','Biossegurança','Farmacologia Básica',
    'Nutrição Clínica','Radiologia','Enfermagem','Fisioterapia',
    'Psicologia Organizacional'
  ],
  'Soft Skills': [
    'Comunicação','Trabalho em equipe','Resolução de problemas',
    'Adaptabilidade','Proatividade','Criatividade','Pensamento crítico',
    'Organização','Gestão do tempo','Inteligência emocional','Didática'
  ],
  'Idiomas': [
    'Inglês Básico','Inglês Intermediário','Inglês Avançado',
    'Espanhol','Francês','Mandarim','Alemão'
  ]
};

const AREAS = [
  'Tecnologia da Informação','Saúde','Engenharia','Administração',
  'Marketing Digital','Design','Educação','Direito','Finanças',
  'Logística','Recursos Humanos','Comércio Exterior','Agronegócio',
  'Meio Ambiente','Arquitetura','Comunicação','Outros'
];

const CURSOS = [
  { id:1,  nome:'Python para Data Science',         plataforma:'Coursera',            duracao:'40h', nivel:'Intermediário', gratis:false, area:'Tecnologia da Informação', skills:['Python','Machine Learning','Análise de Dados'], descricao:'Aprenda Python aplicado à ciência de dados com pandas, numpy e scikit-learn. Ideal para quem quer entrar na área de dados.' },
  { id:2,  nome:'Desenvolvimento Web Completo',      plataforma:'Udemy',               duracao:'65h', nivel:'Iniciante',     gratis:false, area:'Tecnologia da Informação', skills:['HTML/CSS','JavaScript','React','Node.js'], descricao:'Do zero ao fullstack com HTML, CSS, JavaScript, React e Node.js. Mais de 65h de conteúdo prático.' },
  { id:3,  nome:'Excel do Básico ao Avançado',       plataforma:'Fundação Bradesco',   duracao:'20h', nivel:'Iniciante',     gratis:true,  area:'Administração',            skills:['Excel Avançado'], descricao:'Domine planilhas, fórmulas avançadas, tabelas dinâmicas e automação com macros. Certificação gratuita.' },
  { id:4,  nome:'Marketing Digital: Fundamentos',    plataforma:'Google Ateliê Digital',duracao:'15h', nivel:'Iniciante',    gratis:true,  area:'Marketing Digital',        skills:['Marketing Digital','SEO'], descricao:'Fundamentos de marketing digital, SEO, redes sociais e Google Ads. Certificação Google incluída.' },
  { id:5,  nome:'SQL para Análise de Dados',         plataforma:'Alura',               duracao:'30h', nivel:'Iniciante',     gratis:false, area:'Tecnologia da Informação', skills:['SQL','Análise de Dados','Power BI'], descricao:'Aprenda SQL do básico ao avançado para análise e manipulação de dados em bancos relacionais.' },
  { id:6,  nome:'UX Design: Pesquisa e Prototipação',plataforma:'Alura',               duracao:'35h', nivel:'Intermediário', gratis:false, area:'Design',                   skills:['UX/UI Design','Figma'], descricao:'Metodologias de UX, pesquisa com usuários, wireframes e prototipação no Figma.' },
  { id:7,  nome:'Gestão de Projetos com Scrum',      plataforma:'FGV Online',          duracao:'25h', nivel:'Intermediário', gratis:false, area:'Administração',            skills:['Gestão de Projetos','Scrum/Agile'], descricao:'Metodologias ágeis, Scrum, Kanban e gestão de equipes de alto desempenho.' },
  { id:8,  nome:'Inglês para o Mercado de Trabalho', plataforma:'Fundação Bradesco',   duracao:'40h', nivel:'Iniciante',     gratis:true,  area:'Comunicação',              skills:['Inglês Básico','Inglês Intermediário'], descricao:'Inglês profissional com foco em comunicação corporativa, e-mails e apresentações.' },
  { id:9,  nome:'Power BI: Dashboards Profissionais',plataforma:'Microsoft Learn',     duracao:'20h', nivel:'Intermediário', gratis:true,  area:'Tecnologia da Informação', skills:['Power BI','Análise de Dados','Excel Avançado'], descricao:'Crie dashboards interativos e relatórios gerenciais com Power BI Desktop e Service.' },
  { id:10, nome:'Primeiros Socorros e Emergências',  plataforma:'SENAI',               duracao:'16h', nivel:'Iniciante',     gratis:false, area:'Saúde',                    skills:['Primeiros Socorros','Biossegurança'], descricao:'Técnicas de primeiros socorros, RCP, desfibrilação e atendimento a emergências.' },
  { id:11, nome:'Docker e Containers para Devs',     plataforma:'Alura',               duracao:'22h', nivel:'Intermediário', gratis:false, area:'Tecnologia da Informação', skills:['Docker','Linux','Git'], descricao:'Containerização com Docker, docker-compose e boas práticas de DevOps.' },
  { id:12, nome:'Copywriting e Redação Persuasiva',  plataforma:'Udemy',               duracao:'12h', nivel:'Iniciante',     gratis:false, area:'Marketing Digital',        skills:['Copywriting','Marketing Digital'], descricao:'Técnicas de escrita persuasiva para vendas, e-mail marketing e redes sociais.' },
  { id:13, nome:'Machine Learning com Scikit-Learn', plataforma:'Coursera',            duracao:'55h', nivel:'Avançado',      gratis:false, area:'Tecnologia da Informação', skills:['Machine Learning','Python','Inteligência Artificial'], descricao:'Algoritmos de aprendizado de máquina, validação de modelos e deployment em produção.' },
  { id:14, nome:'Gestão Financeira para Negócios',   plataforma:'SEBRAE',              duracao:'18h', nivel:'Iniciante',     gratis:true,  area:'Finanças',                 skills:['Gestão Financeira','Empreendedorismo'], descricao:'Fluxo de caixa, DRE, ponto de equilíbrio e planejamento financeiro empresarial.' },
  { id:15, nome:'React: Criando SPAs Modernas',      plataforma:'Alura',               duracao:'45h', nivel:'Avançado',      gratis:false, area:'Tecnologia da Informação', skills:['React','JavaScript','HTML/CSS'], descricao:'Componentização, hooks, context API e integração com APIs REST.' },
  { id:16, nome:'Segurança da Informação Essencial', plataforma:'Microsoft Learn',     duracao:'30h', nivel:'Intermediário', gratis:true,  area:'Tecnologia da Informação', skills:['Segurança da Informação','Redes de Computadores'], descricao:'Fundamentos de cibersegurança, LGPD, criptografia e proteção de dados.' },
  { id:17, nome:'Design Gráfico com Canva',          plataforma:'YouTube — Design Lab',duracao:'10h', nivel:'Iniciante',     gratis:true,  area:'Design',                   skills:['UX/UI Design'], descricao:'Crie materiais profissionais de marketing, posts e identidade visual com Canva.' },
  { id:18, nome:'Logística e Supply Chain',          plataforma:'FGV Online',          duracao:'35h', nivel:'Intermediário', gratis:false, area:'Logística',                skills:['Planejamento Estratégico','Gestão de Projetos'], descricao:'Gestão da cadeia de suprimentos, estoque, transporte e operações logísticas.' },
  { id:19, nome:'Enfermagem: Cuidados Clínicos',     plataforma:'SENAI',               duracao:'60h', nivel:'Iniciante',     gratis:false, area:'Saúde',                    skills:['Enfermagem','Biossegurança','Primeiros Socorros'], descricao:'Procedimentos básicos de enfermagem, higienização e cuidados ao paciente.' },
  { id:20, nome:'Java para Desenvolvimento Backend', plataforma:'Alura',               duracao:'50h', nivel:'Intermediário', gratis:false, area:'Tecnologia da Informação', skills:['Java','SQL','Git'], descricao:'POO com Java, Spring Boot, APIs REST e integração com banco de dados relacional.' },
  { id:21, nome:'Inteligência Emocional no Trabalho',plataforma:'Coursera',            duracao:'12h', nivel:'Iniciante',     gratis:false, area:'Recursos Humanos',         skills:['Inteligência emocional','Liderança','Gestão de Pessoas'], descricao:'Desenvolvimento de competências emocionais para ambientes corporativos.' },
  { id:22, nome:'SEO Avançado e Google Analytics',   plataforma:'Udemy',               duracao:'25h', nivel:'Avançado',      gratis:false, area:'Marketing Digital',        skills:['SEO','Marketing Digital','Análise de Dados'], descricao:'Otimização para mecanismos de busca, análise de tráfego e conversão.' },
  { id:23, nome:'Liderança e Gestão de Equipes',     plataforma:'FGV Online',          duracao:'20h', nivel:'Intermediário', gratis:false, area:'Administração',            skills:['Liderança','Gestão de Pessoas','Comunicação'], descricao:'Estilos de liderança, feedback, motivação e gestão de conflitos.' },
  { id:24, nome:'Node.js: APIs e Microsserviços',    plataforma:'Alura',               duracao:'40h', nivel:'Avançado',      gratis:false, area:'Tecnologia da Informação', skills:['Node.js','JavaScript','Docker','SQL'], descricao:'APIs RESTful, autenticação JWT, microsserviços e deploy em cloud.' },
  { id:25, nome:'Agronegócio: Gestão e Tecnologia',  plataforma:'SENAR Online',        duracao:'30h', nivel:'Intermediário', gratis:true,  area:'Agronegócio',              skills:['Planejamento Estratégico','Gestão Financeira'], descricao:'Inovação tecnológica no campo, gestão rural e mercado do agronegócio brasileiro.' },
  { id:26, nome:'TypeScript para Front-End Escalável', plataforma:'Alura',             duracao:'28h', nivel:'Intermediário', gratis:false, area:'Tecnologia da Informação', skills:['TypeScript','JavaScript','React'], descricao:'Tipagem estática, boas práticas e organização de aplicações front-end de médio e grande porte.' },
  { id:27, nome:'Go para APIs de Alta Performance',  plataforma:'Full Cycle',          duracao:'32h', nivel:'Avançado',      gratis:false, area:'Tecnologia da Informação', skills:['Go','Docker','PostgreSQL','Git'], descricao:'Criação de APIs rápidas e resilientes com Go, testes automatizados e integração com banco relacional.' },
  { id:28, nome:'Kotlin para Android Moderno',       plataforma:'Udemy',               duracao:'36h', nivel:'Intermediário', gratis:false, area:'Tecnologia da Informação', skills:['Kotlin','Git'], descricao:'Construa apps Android com Kotlin, arquitetura limpa, navegação e integração com APIs REST.' },
  { id:29, nome:'Swift e iOS Essentials',            plataforma:'Coursera',            duracao:'34h', nivel:'Intermediário', gratis:false, area:'Tecnologia da Informação', skills:['Swift','Git'], descricao:'Fundamentos de desenvolvimento iOS com Swift, componentes nativos e publicação de aplicativos.' },
  { id:30, nome:'Rust para Sistemas Confiáveis',     plataforma:'DIO',                 duracao:'26h', nivel:'Avançado',      gratis:true,  area:'Tecnologia da Informação', skills:['Rust','Linux','Git'], descricao:'Aprenda ownership, segurança de memória e desenvolvimento de sistemas confiáveis com Rust.' },
  { id:31, nome:'Vue.js na Prática',                 plataforma:'Alura',               duracao:'24h', nivel:'Intermediário', gratis:false, area:'Tecnologia da Informação', skills:['Vue.js','JavaScript','HTML/CSS'], descricao:'Crie interfaces reativas com Vue, componentes reutilizáveis e integração com APIs.' },
  { id:32, nome:'Angular para Aplicações Corporativas', plataforma:'Udemy',           duracao:'38h', nivel:'Avançado',      gratis:false, area:'Tecnologia da Informação', skills:['Angular','TypeScript','HTML/CSS'], descricao:'Desenvolvimento de SPAs robustas com Angular, RxJS, formulários e arquitetura modular.' },
  { id:33, nome:'Flutter para Apps Multiplataforma', plataforma:'Google Codelabs',    duracao:'30h', nivel:'Intermediário', gratis:true,  area:'Tecnologia da Informação', skills:['Flutter','Dart','Git'], descricao:'Desenvolva apps Android e iOS com uma base única usando Flutter e componentes modernos.' },
  { id:34, nome:'MongoDB para Desenvolvedores',      plataforma:'MongoDB University', duracao:'18h', nivel:'Iniciante',     gratis:true,  area:'Tecnologia da Informação', skills:['MongoDB','Node.js','JavaScript'], descricao:'Modelagem de documentos, consultas, índices e integração com aplicações web.' },
  { id:35, nome:'PostgreSQL Avançado para Back-End', plataforma:'Alura',              duracao:'22h', nivel:'Intermediário', gratis:false, area:'Tecnologia da Informação', skills:['PostgreSQL','SQL','Docker'], descricao:'Consultas avançadas, otimização, procedures e uso profissional do PostgreSQL no back-end.' },
  { id:36, nome:'AWS Cloud Practitioner na Prática', plataforma:'AWS Skill Builder',  duracao:'16h', nivel:'Iniciante',     gratis:true,  area:'Tecnologia da Informação', skills:['AWS','Linux','Docker'], descricao:'Visão geral da nuvem AWS, serviços principais, custos, segurança e fundamentos para certificação.' },
  { id:37, nome:'Direito Digital e LGPD para Empresas', plataforma:'SEBRAE',          duracao:'14h', nivel:'Intermediário', gratis:true,  area:'Direito',                  skills:['Segurança da Informação','Comunicação','Organização'], descricao:'Fundamentos da LGPD, privacidade, contratos digitais e riscos jurídicos no ambiente online.' },
  { id:38, nome:'BIM e Projetos Arquitetônicos no Revit', plataforma:'SENAI',        duracao:'40h', nivel:'Intermediário', gratis:false, area:'Arquitetura',             skills:['AutoCAD','Gestão de Projetos','Organização'], descricao:'Fluxo BIM, detalhamento arquitetônico e compatibilização de projetos com foco em produtividade.' },
  { id:39, nome:'Comércio Exterior na Prática',      plataforma:'FGV Online',         duracao:'20h', nivel:'Intermediário', gratis:false, area:'Comércio Exterior',       skills:['Negociação','Inglês Intermediário','Planejamento Estratégico'], descricao:'Importação, exportação, incoterms e rotinas operacionais para atuar em comércio internacional.' },
  { id:40, nome:'Gestão Ambiental e ESG',            plataforma:'Fundação Bradesco',  duracao:'18h', nivel:'Iniciante',     gratis:true,  area:'Meio Ambiente',           skills:['Planejamento Estratégico','Análise de Dados','Organização'], descricao:'Princípios de sustentabilidade, relatórios ESG e indicadores ambientais para negócios responsáveis.' },
  { id:41, nome:'Didática e Metodologias Ativas',    plataforma:'Coursera',           duracao:'24h', nivel:'Intermediário', gratis:false, area:'Educação',                skills:['Didática','Comunicação','Organização'], descricao:'Aprenda a estruturar aulas engajadoras com metodologias ativas, avaliação formativa e recursos digitais.' },
  { id:42, nome:'Comunicação Corporativa e Storytelling', plataforma:'Udemy',        duracao:'15h', nivel:'Iniciante',     gratis:false, area:'Comunicação',             skills:['Comunicação','Copywriting','Criatividade'], descricao:'Técnicas para criar mensagens claras, apresentações memoráveis e narrativas estratégicas para empresas.' },
  { id:43, nome:'Finanças com Power BI e SQL',       plataforma:'Microsoft Learn',    duracao:'20h', nivel:'Intermediário', gratis:true,  area:'Finanças',                skills:['Power BI','SQL','Gestão Financeira','Análise de Dados'], descricao:'Integre dados financeiros, monte dashboards gerenciais e gere insights com SQL e Power BI.' },
  { id:44, nome:'Engenharia de Dados com Python e SQL', plataforma:'DataCamp',       duracao:'42h', nivel:'Avançado',      gratis:false, area:'Tecnologia da Informação', skills:['Python','SQL','PostgreSQL','Docker'], descricao:'Pipelines de dados, ingestão, transformação e modelagem para times de analytics e engenharia.' },
  { id:45, nome:'C# e .NET para Sistemas Web',       plataforma:'Alura',              duracao:'34h', nivel:'Intermediário', gratis:false, area:'Tecnologia da Informação', skills:['C#','.NET','SQL','Git'], descricao:'Crie aplicações web com ASP.NET, APIs, autenticação e integração com bancos relacionais.' },
  { id:46, nome:'Ruby on Rails para SaaS',           plataforma:'Udemy',              duracao:'28h', nivel:'Intermediário', gratis:false, area:'Tecnologia da Informação', skills:['Ruby','SQL','Git','PostgreSQL'], descricao:'Desenvolvimento rápido de produtos SaaS com Rails, autenticação e deploy em produção.' },
  { id:47, nome:'Cibersegurança Ofensiva: Pentest Foundations', plataforma:'DIO',    duracao:'22h', nivel:'Avançado',      gratis:true,  area:'Tecnologia da Informação', skills:['Segurança da Informação','Linux','Redes de Computadores'], descricao:'Mapeamento de vulnerabilidades, análise de superfícies de ataque e fundamentos éticos de pentest.' },
  { id:48, nome:'Gestão de Produto Digital',         plataforma:'PM3',                duracao:'20h', nivel:'Intermediário', gratis:false, area:'Administração',            skills:['Scrum/Agile','Análise de Dados','Comunicação'], descricao:'Priorize backlog, conduza discovery e alinhe times de tecnologia e negócio em produtos digitais.' },
  { id:49, nome:'Inglês para TI e Entrevistas Técnicas', plataforma:'YouTube — Tech Fluency', duracao:'12h', nivel:'Intermediário', gratis:true, area:'Comunicação', skills:['Inglês Intermediário','Comunicação'], descricao:'Vocabulário técnico, apresentações em inglês e preparação para entrevistas com empresas de tecnologia.' },
  { id:50, nome:'AutoCAD para Engenharia Civil',     plataforma:'SENAI',              duracao:'26h', nivel:'Iniciante',     gratis:false, area:'Engenharia',              skills:['AutoCAD','Gestão de Projetos','Organização'], descricao:'Desenho técnico, leitura de plantas e documentação de projetos para obras e infraestrutura.' }
];

const VAGAS = [
  { id:1,  cargo:'Analista de Dados Jr',          empresa:'DataVision Consultoria',   cidade:'São Paulo - SP',    modalidade:'Híbrido',   tipo:'CLT',     area:'Tecnologia da Informação', skills:['SQL','Power BI','Python','Excel Avançado'],           descricao:'Responsável por análise e visualização de dados para apoio à tomada de decisão estratégica. Trabalhará com grandes volumes de dados e construção de relatórios.',          requisitos:['SQL intermediário','Excel Avançado','Desejável Power BI','Comunicação clara'], beneficios:['Vale Refeição R$45/dia','Plano de Saúde Unimed','PLR','Home Office 3x/semana'] },
  { id:2,  cargo:'Estágio em Marketing Digital',  empresa:'Agência Impulso Digital',  cidade:'Remoto',            modalidade:'Remoto',    tipo:'Estágio', area:'Marketing Digital',        skills:['Marketing Digital','SEO','Copywriting'],              descricao:'Auxílio na criação de conteúdo para redes sociais, gestão de campanhas Google Ads e análise de métricas de marketing digital.',                                          requisitos:['Cursando Marketing, Comunicação ou afins','Canva básico','Boa escrita'], beneficios:['Bolsa R$ 1.200','Vale Transporte','Flexibilidade de horário'] },
  { id:3,  cargo:'Desenvolvedor Front-End Jr',    empresa:'TechSoft Sistemas',        cidade:'Curitiba - PR',     modalidade:'Presencial', tipo:'CLT',    area:'Tecnologia da Informação', skills:['HTML/CSS','JavaScript','React','Git'],                descricao:'Desenvolvimento de interfaces web modernas e responsivas usando React e boas práticas de acessibilidade. Participação em code reviews.',                                  requisitos:['React.js','HTML/CSS avançado','Git','Inglês Técnico'], beneficios:['Plano de Saúde','VR R$50/dia','Gympass','13° Salário'] },
  { id:4,  cargo:'Assistente Administrativo',     empresa:'Grupo Evolução Comercial', cidade:'Belo Horizonte - MG',modalidade:'Presencial',tipo:'CLT',    area:'Administração',            skills:['Excel Avançado','Atendimento ao Cliente','Organização'],descricao:'Apoio administrativo geral, controle de documentos, atendimento a fornecedores e clientes, suporte à equipe gerencial.',                                                    requisitos:['Ensino Médio completo','Excel básico/intermediário','Boa comunicação'], beneficios:['Vale Transporte','Vale Refeição','Plano Odontológico'] },
  { id:5,  cargo:'Técnico de Enfermagem',         empresa:'Hospital São Lucas',       cidade:'Rio de Janeiro - RJ',modalidade:'Presencial',tipo:'CLT',    area:'Saúde',                    skills:['Enfermagem','Biossegurança','Primeiros Socorros'],    descricao:'Assistência direta ao paciente, execução de procedimentos de enfermagem e suporte às equipes médicas nos plantões.',                                                    requisitos:['CTE ativo','Habilitação técnica de enfermagem','Disponibilidade para plantão'], beneficios:['Plano de Saúde','Refeição no Local','Adicional Noturno','Uniforme'] },
  { id:6,  cargo:'Designer UX/UI Jr',             empresa:'Creative Labs Studio',     cidade:'Remoto',            modalidade:'Remoto',    tipo:'PJ',      area:'Design',                   skills:['UX/UI Design','Figma'],                               descricao:'Criação de protótipos interativos, wireframes e interfaces centradas no usuário para aplicativos e web. Participação em design system.',                                 requisitos:['Figma avançado','Portfolio obrigatório','Noções de HTML/CSS'], beneficios:['PJ R$ 4.500/mês','Horário Flexível','Equipamento fornecido'] },
  { id:7,  cargo:'Analista de RH',                empresa:'Conecta Talentos RH',      cidade:'São Paulo - SP',    modalidade:'Híbrido',   tipo:'CLT',     area:'Recursos Humanos',         skills:['Gestão de Pessoas','Psicologia Organizacional'],      descricao:'Recrutamento e seleção, processos de onboarding, treinamentos e desenvolvimento e gestão de clima organizacional.',                                                     requisitos:['Superior em Psicologia ou RH','Excel intermediário','Experiência em R&S'], beneficios:['Plano de Saúde','VA R$ 800/mês','PLR','Horário Flexível'] },
  { id:8,  cargo:'Estágio em Engenharia Civil',   empresa:'Construtora Horizonte',    cidade:'Porto Alegre - RS', modalidade:'Presencial', tipo:'Estágio',area:'Engenharia',               skills:['Excel Avançado','Gestão de Projetos'],                descricao:'Acompanhamento de obras, elaboração de orçamentos, controle de cronogramas e organização da documentação técnica de projetos.',                                          requisitos:['Cursando Eng. Civil (4° ao 8° período)','AutoCAD básico'], beneficios:['Bolsa R$ 1.500','Vale Transporte','Mentoria com Engenheiro Sênior'] },
  { id:9,  cargo:'Trainee Financeiro',            empresa:'FinanceGroup Brasil',      cidade:'Campinas - SP',     modalidade:'Presencial', tipo:'Trainee',area:'Finanças',                 skills:['Gestão Financeira','Excel Avançado','Análise de Dados','SQL'], descricao:'Programa trainee com rotação por áreas de controladoria, tesouraria e planejamento financeiro. Desenvolvimento acelerado.',                               requisitos:['Recém-formado (máx. 2 anos)','Excel avançado','Inglês intermediário'], beneficios:['R$ 4.200','Plano de Saúde','Participação em Resultados','Mentoria Executiva'] },
  { id:10, cargo:'Analista de Logística',         empresa:'LogisBrasil Transportes',  cidade:'Guarulhos - SP',    modalidade:'Presencial', tipo:'CLT',    area:'Logística',                skills:['Logística','Excel Avançado','Planejamento Estratégico'], descricao:'Controle de estoque, roteirização de entregas, gestão de indicadores de desempenho e relacionamento com transportadoras.',                                             requisitos:['Superior em Logística ou Administração','Excel avançado','ERP básico'], beneficios:['VT + VR','Plano de Saúde','Seguro de Vida','PLR'] },
  { id:11, cargo:'Dev Backend Python',            empresa:'InnovateTech Startup',     cidade:'Remoto',            modalidade:'Remoto',    tipo:'CLT',     area:'Tecnologia da Informação', skills:['Python','SQL','Docker','Git'],                         descricao:'Desenvolvimento de APIs e microsserviços em Python com Django e FastAPI. Participação em decisões de arquitetura e infraestrutura.',                                    requisitos:['Python intermediário/avançado','SQL','Git','Inglês Técnico'], beneficios:['Salário até R$ 7.000','100% Remoto','Stock Options','Plano de Saúde'] },
  { id:12, cargo:'Especialista em SEO',           empresa:'MarketUp Digital',         cidade:'Rio de Janeiro - RJ',modalidade:'Híbrido',   tipo:'CLT',    area:'Marketing Digital',        skills:['SEO','Marketing Digital','Copywriting','Análise de Dados'], descricao:'Estratégias de SEO on/off-page, análise de performance, link building e otimização de conteúdo para diferentes segmentos.',                                        requisitos:['Experiência comprovada com SEO','Google Analytics','WordPress'], beneficios:['Plano de Saúde','VA','Cursos Patrocinados','Bônus por Metas'] },
  { id:13, cargo:'Enfermeiro Assistencial',       empresa:'Clínica Bem Estar',        cidade:'Fortaleza - CE',    modalidade:'Presencial', tipo:'CLT',    area:'Saúde',                    skills:['Enfermagem','Liderança','Biossegurança'],             descricao:'Gerenciamento da equipe de técnicos, supervisão de procedimentos clínicos e gestão de qualidade no atendimento ao paciente.',                                         requisitos:['COREN ativo','Experiência hospitalar','Liderança de equipes'], beneficios:['Plano de Saúde Premium','Vale Refeição','Plano Odontológico'] },
  { id:14, cargo:'Analista de Marketing Jr',      empresa:'BrandMasters Comunicação', cidade:'São Paulo - SP',    modalidade:'Híbrido',   tipo:'CLT',     area:'Marketing Digital',        skills:['Marketing Digital','Análise de Dados','Copywriting','SEO'], descricao:'Planejamento e execução de campanhas digitais, análise de métricas e gestão de conteúdo para múltiplos canais.',                                                   requisitos:['Superior em Marketing ou Comunicação','Google Analytics','Redes Sociais'], beneficios:['VR R$ 750','Plano de Saúde','Horário Flexível'] },
  { id:15, cargo:'Assistente de RH',              empresa:'GestãoPro Consultoria',    cidade:'Brasília - DF',     modalidade:'Presencial', tipo:'CLT',    area:'Recursos Humanos',         skills:['Gestão de Pessoas','Atendimento ao Cliente','Excel Avançado'], descricao:'Apoio ao departamento de RH: controle de ponto, benefícios, admissão e demissão, folha de pagamento e arquivos de pessoal.',                                        requisitos:['Cursando ou formado em RH/Psicologia','Excel intermediário','Discrição'], beneficios:['VT + VR','Plano de Saúde','Estabilidade'] },
  { id:16, cargo:'Full Stack Developer Pleno',    empresa:'CloudSolutions Tech',      cidade:'Remoto',            modalidade:'Remoto',    tipo:'PJ',      area:'Tecnologia da Informação', skills:['React','Node.js','SQL','Docker','Git'],               descricao:'Desenvolvimento de aplicações web completas do front ao back, arquitetura de sistemas, code review e mentoria de devs júnior.',                                         requisitos:['React + Node.js','SQL/NoSQL','Docker','Inglês Intermediário'], beneficios:['PJ R$ 9.000–12.000','100% Remoto','Horário Flexível'] },
  { id:17, cargo:'Analista Financeiro Jr',        empresa:'Investia Capital',         cidade:'São Paulo - SP',    modalidade:'Presencial', tipo:'CLT',    area:'Finanças',                 skills:['Gestão Financeira','Excel Avançado','Análise de Dados'], descricao:'Análise de demonstrativos financeiros, elaboração de projeções e relatórios gerenciais para suporte à diretoria.',                                                      requisitos:['Formado em Contábeis/Economia/Administração','Excel Avançado'], beneficios:['Plano de Saúde','PLR','VR/VA','Ambiente Moderno'] },
  { id:18, cargo:'Coordenador de Logística',      empresa:'Express Cargo Logística',  cidade:'Santos - SP',       modalidade:'Presencial', tipo:'CLT',    area:'Logística',                skills:['Logística','Liderança','Planejamento Estratégico','Excel Avançado'], descricao:'Coordenação de operações portuárias, gestão de equipe de 15 colaboradores e controle de indicadores operacionais.',                                             requisitos:['Superior em Logística ou Comércio Exterior','Experiência 3+ anos','Inglês Básico'], beneficios:['Salário até R$ 6.500','Plano de Saúde','PLR','VR/VA'] },
  { id:19, cargo:'Desenvolvedor Front-End TypeScript', empresa:'NeonStack Digital', cidade:'Remoto',            modalidade:'Remoto',    tipo:'CLT',    area:'Tecnologia da Informação', skills:['TypeScript','React','JavaScript','Git'],            descricao:'Construção de interfaces escaláveis com React e TypeScript, integração com APIs e foco em qualidade de código.',                                                       requisitos:['TypeScript intermediário','React','Git','Boas práticas de componentização'], beneficios:['Plano de Saúde','Auxílio Home Office','PLR','Horário Flexível'] },
  { id:20, cargo:'Engenheiro de Software Go',     empresa:'Velocity APIs',            cidade:'São Paulo - SP',    modalidade:'Híbrido',   tipo:'CLT',    area:'Tecnologia da Informação', skills:['Go','Docker','PostgreSQL','Git'],                   descricao:'Desenvolvimento de serviços de alta performance para ecossistema financeiro, com foco em escalabilidade e observabilidade.',                                           requisitos:['Experiência com Go','Docker','Banco relacional','Testes automatizados'], beneficios:['Bônus anual','Plano de Saúde Premium','VR/VA','Home Office 2x/semana'] },
  { id:21, cargo:'Desenvolvedor Android Kotlin',  empresa:'Orbit Mobile Labs',        cidade:'Belo Horizonte - MG',modalidade:'Híbrido',  tipo:'CLT',    area:'Tecnologia da Informação', skills:['Kotlin','Git'],                                         descricao:'Criação de funcionalidades para app Android, integração com APIs e melhoria contínua da experiência mobile.',                                                           requisitos:['Kotlin','Android Studio','Git','Consumo de APIs REST'], beneficios:['Plano de Saúde','Vale Refeição','Auxílio Educação'] },
  { id:22, cargo:'Desenvolvedor iOS Swift',       empresa:'BluePixel Apps',           cidade:'Remoto',            modalidade:'Remoto',    tipo:'PJ',     area:'Tecnologia da Informação', skills:['Swift','Git'],                                          descricao:'Desenvolvimento de app iOS com foco em performance, usabilidade e integração com serviços em nuvem.',                                                                  requisitos:['Swift','UIKit ou SwiftUI','Git','Publicação em App Store'], beneficios:['PJ R$ 8.000/mês','Horário Flexível','Bônus por entregas'] },
  { id:23, cargo:'Desenvolvedor Flutter',         empresa:'CrossWave Studio',         cidade:'Recife - PE',       modalidade:'Remoto',    tipo:'CLT',    area:'Tecnologia da Informação', skills:['Flutter','Dart','Git'],                                 descricao:'Criação de aplicativos multiplataforma para clientes de varejo e educação, com entregas rápidas e boa qualidade visual.',                                              requisitos:['Flutter','Dart','Git','Gerenciamento de estado'], beneficios:['100% Remoto','VR','Plano de Saúde','Day Off no aniversário'] },
  { id:24, cargo:'Desenvolvedor Ruby on Rails',   empresa:'SaaS Village',             cidade:'Remoto',            modalidade:'Remoto',    tipo:'PJ',     area:'Tecnologia da Informação', skills:['Ruby','SQL','Git','PostgreSQL'],                       descricao:'Evolução de plataforma SaaS B2B, construção de novas features e manutenção de integrações com parceiros.',                                                            requisitos:['Ruby on Rails','PostgreSQL','Git','APIs REST'], beneficios:['PJ R$ 9.500/mês','Equipamento fornecido','Recesso remunerado'] },
  { id:25, cargo:'Desenvolvedor .NET Pleno',      empresa:'CoreSphere Sistemas',      cidade:'Campinas - SP',     modalidade:'Híbrido',   tipo:'CLT',    area:'Tecnologia da Informação', skills:['C#','.NET','SQL','Docker'],                            descricao:'Desenvolvimento de APIs e sistemas internos com .NET, testes e integração com containers.',                                                                           requisitos:['C#','ASP.NET','SQL','Docker'], beneficios:['Plano de Saúde','Vale Refeição','PLR','Auxílio Mobilidade'] },
  { id:26, cargo:'Desenvolvedor Vue.js',          empresa:'Studio Pixel Web',         cidade:'Curitiba - PR',     modalidade:'Presencial', tipo:'CLT',   area:'Tecnologia da Informação', skills:['Vue.js','JavaScript','HTML/CSS'],                       descricao:'Construção de dashboards e portais administrativos com Vue.js, componentes reutilizáveis e integração contínua.',                                                    requisitos:['Vue.js','JavaScript moderno','CSS responsivo'], beneficios:['Plano Odontológico','VR','Gympass'] },
  { id:27, cargo:'Desenvolvedor Angular',         empresa:'CorpTech Soluções',        cidade:'São Paulo - SP',    modalidade:'Híbrido',   tipo:'CLT',    area:'Tecnologia da Informação', skills:['Angular','TypeScript','HTML/CSS'],                     descricao:'Atuação em aplicações corporativas com Angular, formulários complexos e integração com serviços internos.',                                                           requisitos:['Angular','TypeScript','RxJS','Consumo de APIs'], beneficios:['PLR','Plano de Saúde','Home Office parcial'] },
  { id:28, cargo:'Administrador PostgreSQL',      empresa:'Banco Delta Digital',      cidade:'Brasília - DF',     modalidade:'Híbrido',   tipo:'CLT',    area:'Tecnologia da Informação', skills:['PostgreSQL','SQL','Linux'],                             descricao:'Administração, monitoramento e otimização de ambientes PostgreSQL críticos para operação do negócio.',                                                                 requisitos:['PostgreSQL','Tuning','Backup e recovery','Linux'], beneficios:['Plano de Saúde Premium','VA R$ 900','Seguro de Vida'] },
  { id:29, cargo:'Cloud Engineer AWS Jr',         empresa:'SkyOps Cloud',             cidade:'Remoto',            modalidade:'Remoto',    tipo:'CLT',    area:'Tecnologia da Informação', skills:['AWS','Docker','Linux','Git'],                           descricao:'Suporte à infraestrutura cloud, automações de deploy e observabilidade para times de produto.',                                                                       requisitos:['AWS básico/intermediário','Docker','Linux','Git'], beneficios:['Certificações pagas','Home Office','Plano de Saúde'] },
  { id:30, cargo:'Analista de Cibersegurança',    empresa:'ShieldSec Brasil',         cidade:'Rio de Janeiro - RJ',modalidade:'Híbrido',  tipo:'CLT',    area:'Tecnologia da Informação', skills:['Segurança da Informação','Linux','Redes de Computadores'], descricao:'Monitoramento de incidentes, resposta a alertas, revisão de acessos e melhoria de postura de segurança.',                                                             requisitos:['Redes','Linux','Segurança da Informação','Desejável SIEM'], beneficios:['Adicional de Certificação','Plano de Saúde','VR','PLR'] },
  { id:31, cargo:'Analista de Comércio Exterior', empresa:'GlobalPort Trading',       cidade:'Santos - SP',       modalidade:'Presencial', tipo:'CLT',   area:'Comércio Exterior',       skills:['Negociação','Inglês Intermediário','Planejamento Estratégico'], descricao:'Acompanhamento de processos de importação e exportação, contato com despachantes e análise documental.',                                                          requisitos:['Inglês intermediário','Conhecimento em incoterms','Organização'], beneficios:['VT','VR','Plano Odontológico','Bônus anual'] },
  { id:32, cargo:'Arquiteto(a) BIM Júnior',       empresa:'Traço Urbano Projetos',    cidade:'Porto Alegre - RS', modalidade:'Híbrido',   tipo:'CLT',    area:'Arquitetura',             skills:['AutoCAD','Gestão de Projetos','Organização'],        descricao:'Desenvolvimento de projetos arquitetônicos com fluxo BIM e compatibilização com equipes multidisciplinares.',                                                         requisitos:['Revit ou AutoCAD','Leitura de projeto','Formação em Arquitetura'], beneficios:['Vale Alimentação','Plano de Saúde','Auxílio Curso'] },
  { id:33, cargo:'Analista ESG',                  empresa:'Verde Futuro Consultoria', cidade:'São Paulo - SP',    modalidade:'Híbrido',   tipo:'CLT',    area:'Meio Ambiente',           skills:['Análise de Dados','Planejamento Estratégico','Organização'], descricao:'Coleta de indicadores, elaboração de relatórios e apoio à implementação de iniciativas ESG em clientes corporativos.',                                            requisitos:['Excel ou Power BI','Interesse em ESG','Boa comunicação'], beneficios:['Plano de Saúde','VR','Modelo híbrido'] },
  { id:34, cargo:'Professor(a) Assistente EAD',   empresa:'Instituto Saber Online',   cidade:'Remoto',            modalidade:'Remoto',    tipo:'Freelance',area:'Educação',             skills:['Didática','Comunicação','Organização'],              descricao:'Apoio na criação de atividades, acompanhamento de turmas e mediação em ambientes virtuais de aprendizagem.',                                                        requisitos:['Experiência com ensino online','Comunicação clara','Organização'], beneficios:['Pagamento por turma','100% remoto','Horário flexível'] },
  { id:35, cargo:'Especialista em Comunicação Interna', empresa:'Grupo Harmonia',   cidade:'São Paulo - SP',    modalidade:'Híbrido',   tipo:'CLT',    area:'Comunicação',             skills:['Comunicação','Copywriting','Criatividade'],          descricao:'Planejamento de campanhas internas, produção de textos e iniciativas de engajamento para colaboradores.',                                                             requisitos:['Redação excelente','Experiência com comunicação corporativa','Criatividade'], beneficios:['Plano de Saúde','VA','Day Off','Auxílio Cultura'] },
  { id:36, cargo:'Analista Jurídico LGPD',        empresa:'LexData Consultoria',      cidade:'Remoto',            modalidade:'Remoto',    tipo:'CLT',    area:'Direito',                  skills:['Segurança da Informação','Comunicação','Organização'], descricao:'Apoio em adequação à LGPD, revisão documental, mapeamento de processos e orientação a clientes.',                                                                   requisitos:['Formação em Direito','Conhecimento em privacidade','Boa escrita'], beneficios:['Home Office','Plano de Saúde','Bônus semestral'] },
  { id:37, cargo:'Cientista de Dados Júnior',     empresa:'Nexa Insights',            cidade:'Remoto',            modalidade:'Remoto',    tipo:'CLT',    area:'Tecnologia da Informação', skills:['Python','SQL','Machine Learning','Power BI'],         descricao:'Construção de análises preditivas, preparação de dados e apoio a projetos de machine learning em produtos digitais.',                                                 requisitos:['Python','SQL','Estatística básica','Desejável Power BI'], beneficios:['100% remoto','Plano de Saúde','Auxílio educação'] },
  { id:38, cargo:'Product Analyst',               empresa:'Orbit Products',           cidade:'São Paulo - SP',    modalidade:'Híbrido',   tipo:'CLT',    area:'Administração',            skills:['Scrum/Agile','Análise de Dados','Comunicação'],      descricao:'Apoio ao time de produto com análise de métricas, priorização de backlog e alinhamento com áreas de negócio.',                                                      requisitos:['Análise de dados','Metodologias ágeis','Boa comunicação'], beneficios:['PLR','Plano de Saúde','Home Office parcial'] },
  { id:39, cargo:'Analista Financeiro BI',        empresa:'Atlas Capital',            cidade:'Belo Horizonte - MG',modalidade:'Presencial',tipo:'CLT',    area:'Finanças',                 skills:['Power BI','SQL','Excel Avançado','Gestão Financeira'], descricao:'Criação de relatórios, indicadores e dashboards financeiros para suporte à diretoria.',                                                                           requisitos:['Power BI','Excel avançado','Noções de SQL'], beneficios:['Plano de Saúde','VR','Participação nos resultados'] },
  { id:40, cargo:'Engenheiro Civil de Orçamentos',empresa:'Construmax Engenharia',    cidade:'Curitiba - PR',     modalidade:'Presencial', tipo:'CLT',   area:'Engenharia',               skills:['AutoCAD','Excel Avançado','Gestão de Projetos'],     descricao:'Levantamento quantitativo, elaboração de orçamentos e apoio ao planejamento físico-financeiro de obras.',                                                           requisitos:['Engenharia Civil','AutoCAD','Excel avançado'], beneficios:['Vale Transporte','Refeição no Local','Plano Odontológico'] }
];
