// CarreiraMais — Mock Data

const SKILLS_CATEGORIES = {
  'Tecnologia': [
    'Python','JavaScript','HTML/CSS','Java','SQL','Excel Avançado','Power BI',
    'Git','Linux','Docker','Machine Learning','Inteligência Artificial',
    'Segurança da Informação','Redes de Computadores','UX/UI Design',
    'Figma','React','Node.js','C#','PHP'
  ],
  'Negócios e Gestão': [
    'Gestão de Projetos','Scrum/Agile','Liderança','Negociação',
    'Atendimento ao Cliente','Gestão Financeira','Empreendedorismo',
    'Marketing Digital','SEO','Copywriting','Análise de Dados',
    'Gestão de Pessoas','Planejamento Estratégico'
  ],
  'Saúde': [
    'Primeiros Socorros','Biossegurança','Farmacologia Básica',
    'Nutrição Clínica','Radiologia','Enfermagem','Fisioterapia',
    'Psicologia Organizacional'
  ],
  'Soft Skills': [
    'Comunicação','Trabalho em equipe','Resolução de problemas',
    'Adaptabilidade','Proatividade','Criatividade','Pensamento crítico',
    'Organização','Gestão do tempo','Inteligência emocional'
  ],
  'Idiomas': [
    'Inglês Básico','Inglês Intermediário','Inglês Avançado',
    'Espanhol','Francês','Mandarim','Alemão'
  ]
};

const AREAS = [
  'Tecnologia da Informação','Saúde','Engenharia','Administração',
  'Marketing Digital','Design','Educação','Direito','Finanças',
  'Logística','Recursos Humanos','Comércio Exterior','Agronegócio',
  'Meio Ambiente','Arquitetura','Comunicação','Outros'
];

const CURSOS = [
  { id:1,  nome:'Python para Data Science',         plataforma:'Coursera',            duracao:'40h', nivel:'Intermediário', gratis:false, area:'Tecnologia da Informação', skills:['Python','Machine Learning','Análise de Dados'], descricao:'Aprenda Python aplicado à ciência de dados com pandas, numpy e scikit-learn. Ideal para quem quer entrar na área de dados.' },
  { id:2,  nome:'Desenvolvimento Web Completo',      plataforma:'Udemy',               duracao:'65h', nivel:'Iniciante',     gratis:false, area:'Tecnologia da Informação', skills:['HTML/CSS','JavaScript','React','Node.js'], descricao:'Do zero ao fullstack com HTML, CSS, JavaScript, React e Node.js. Mais de 65h de conteúdo prático.' },
  { id:3,  nome:'Excel do Básico ao Avançado',       plataforma:'Fundação Bradesco',   duracao:'20h', nivel:'Iniciante',     gratis:true,  area:'Administração',            skills:['Excel Avançado'], descricao:'Domine planilhas, fórmulas avançadas, tabelas dinâmicas e automação com macros. Certificação gratuita.' },
  { id:4,  nome:'Marketing Digital: Fundamentos',    plataforma:'Google Ateliê Digital',duracao:'15h', nivel:'Iniciante',    gratis:true,  area:'Marketing Digital',        skills:['Marketing Digital','SEO'], descricao:'Fundamentos de marketing digital, SEO, redes sociais e Google Ads. Certificação Google incluída.' },
  { id:5,  nome:'SQL para Análise de Dados',         plataforma:'Alura',               duracao:'30h', nivel:'Iniciante',     gratis:false, area:'Tecnologia da Informação', skills:['SQL','Análise de Dados','Power BI'], descricao:'Aprenda SQL do básico ao avançado para análise e manipulação de dados em bancos relacionais.' },
  { id:6,  nome:'UX Design: Pesquisa e Prototipação',plataforma:'Alura',               duracao:'35h', nivel:'Intermediário', gratis:false, area:'Design',                   skills:['UX/UI Design','Figma'], descricao:'Metodologias de UX, pesquisa com usuários, wireframes e prototipação no Figma.' },
  { id:7,  nome:'Gestão de Projetos com Scrum',      plataforma:'FGV Online',          duracao:'25h', nivel:'Intermediário', gratis:false, area:'Administração',            skills:['Gestão de Projetos','Scrum/Agile'], descricao:'Metodologias ágeis, Scrum, Kanban e gestão de equipes de alto desempenho.' },
  { id:8,  nome:'Inglês para o Mercado de Trabalho', plataforma:'Fundação Bradesco',   duracao:'40h', nivel:'Iniciante',     gratis:true,  area:'Comunicação',              skills:['Inglês Básico','Inglês Intermediário'], descricao:'Inglês profissional com foco em comunicação corporativa, e-mails e apresentações.' },
  { id:9,  nome:'Power BI: Dashboards Profissionais',plataforma:'Microsoft Learn',     duracao:'20h', nivel:'Intermediário', gratis:true,  area:'Tecnologia da Informação', skills:['Power BI','Análise de Dados','Excel Avançado'], descricao:'Crie dashboards interativos e relatórios gerenciais com Power BI Desktop e Service.' },
  { id:10, nome:'Primeiros Socorros e Emergências',  plataforma:'SENAI',               duracao:'16h', nivel:'Iniciante',     gratis:false, area:'Saúde',                    skills:['Primeiros Socorros','Biossegurança'], descricao:'Técnicas de primeiros socorros, RCP, desfibrilação e atendimento a emergências.' },
  { id:11, nome:'Docker e Containers para Devs',     plataforma:'Alura',               duracao:'22h', nivel:'Intermediário', gratis:false, area:'Tecnologia da Informação', skills:['Docker','Linux','Git'], descricao:'Containerização com Docker, docker-compose e boas práticas de DevOps.' },
  { id:12, nome:'Copywriting e Redação Persuasiva',  plataforma:'Udemy',               duracao:'12h', nivel:'Iniciante',     gratis:false, area:'Marketing Digital',        skills:['Copywriting','Marketing Digital'], descricao:'Técnicas de escrita persuasiva para vendas, e-mail marketing e redes sociais.' },
  { id:13, nome:'Machine Learning com Scikit-Learn', plataforma:'Coursera',            duracao:'55h', nivel:'Avançado',      gratis:false, area:'Tecnologia da Informação', skills:['Machine Learning','Python','Inteligência Artificial'], descricao:'Algoritmos de aprendizado de máquina, validação de modelos e deployment em produção.' },
  { id:14, nome:'Gestão Financeira para Negócios',   plataforma:'SEBRAE',              duracao:'18h', nivel:'Iniciante',     gratis:true,  area:'Finanças',                 skills:['Gestão Financeira','Empreendedorismo'], descricao:'Fluxo de caixa, DRE, ponto de equilíbrio e planejamento financeiro empresarial.' },
  { id:15, nome:'React: Criando SPAs Modernas',      plataforma:'Alura',               duracao:'45h', nivel:'Avançado',      gratis:false, area:'Tecnologia da Informação', skills:['React','JavaScript','HTML/CSS'], descricao:'Componentização, hooks, context API e integração com APIs REST.' },
  { id:16, nome:'Segurança da Informação Essencial', plataforma:'Microsoft Learn',     duracao:'30h', nivel:'Intermediário', gratis:true,  area:'Tecnologia da Informação', skills:['Segurança da Informação','Redes de Computadores'], descricao:'Fundamentos de cibersegurança, LGPD, criptografia e proteção de dados.' },
  { id:17, nome:'Design Gráfico com Canva',          plataforma:'YouTube — Design Lab',duracao:'10h', nivel:'Iniciante',     gratis:true,  area:'Design',                   skills:['UX/UI Design'], descricao:'Crie materiais profissionais de marketing, posts e identidade visual com Canva.' },
  { id:18, nome:'Logística e Supply Chain',          plataforma:'FGV Online',          duracao:'35h', nivel:'Intermediário', gratis:false, area:'Logística',                skills:['Planejamento Estratégico','Gestão de Projetos'], descricao:'Gestão da cadeia de suprimentos, estoque, transporte e operações logísticas.' },
  { id:19, nome:'Enfermagem: Cuidados Clínicos',     plataforma:'SENAI',               duracao:'60h', nivel:'Iniciante',     gratis:false, area:'Saúde',                    skills:['Enfermagem','Biossegurança','Primeiros Socorros'], descricao:'Procedimentos básicos de enfermagem, higienização e cuidados ao paciente.' },
  { id:20, nome:'Java para Desenvolvimento Backend', plataforma:'Alura',               duracao:'50h', nivel:'Intermediário', gratis:false, area:'Tecnologia da Informação', skills:['Java','SQL','Git'], descricao:'POO com Java, Spring Boot, APIs REST e integração com banco de dados relacional.' },
  { id:21, nome:'Inteligência Emocional no Trabalho',plataforma:'Coursera',            duracao:'12h', nivel:'Iniciante',     gratis:false, area:'Recursos Humanos',         skills:['Inteligência emocional','Liderança','Gestão de Pessoas'], descricao:'Desenvolvimento de competências emocionais para ambientes corporativos.' },
  { id:22, nome:'SEO Avançado e Google Analytics',   plataforma:'Udemy',               duracao:'25h', nivel:'Avançado',      gratis:false, area:'Marketing Digital',        skills:['SEO','Marketing Digital','Análise de Dados'], descricao:'Otimização para mecanismos de busca, análise de tráfego e conversão.' },
  { id:23, nome:'Liderança e Gestão de Equipes',     plataforma:'FGV Online',          duracao:'20h', nivel:'Intermediário', gratis:false, area:'Administração',            skills:['Liderança','Gestão de Pessoas','Comunicação'], descricao:'Estilos de liderança, feedback, motivação e gestão de conflitos.' },
  { id:24, nome:'Node.js: APIs e Microsserviços',    plataforma:'Alura',               duracao:'40h', nivel:'Avançado',      gratis:false, area:'Tecnologia da Informação', skills:['Node.js','JavaScript','Docker','SQL'], descricao:'APIs RESTful, autenticação JWT, microsserviços e deploy em cloud.' },
  { id:25, nome:'Agronegócio: Gestão e Tecnologia',  plataforma:'SENAR Online',        duracao:'30h', nivel:'Intermediário', gratis:true,  area:'Agronegócio',              skills:['Planejamento Estratégico','Gestão Financeira'], descricao:'Inovação tecnológica no campo, gestão rural e mercado do agronegócio brasileiro.' }
];

const VAGAS = [
  { id:1,  cargo:'Analista de Dados Jr',          empresa:'DataVision Consultoria',   cidade:'São Paulo - SP',    modalidade:'Híbrido',   tipo:'CLT',     area:'Tecnologia da Informação', skills:['SQL','Power BI','Python','Excel Avançado'],           descricao:'Responsável por análise e visualização de dados para apoio à tomada de decisão estratégica. Trabalhará com grandes volumes de dados e construção de relatórios.',          requisitos:['SQL intermediário','Excel Avançado','Desejável Power BI','Comunicação clara'], beneficios:['Vale Refeição R$45/dia','Plano de Saúde Unimed','PLR','Home Office 3x/semana'] },
  { id:2,  cargo:'Estágio em Marketing Digital',  empresa:'Agência Impulso Digital',  cidade:'Remoto',            modalidade:'Remoto',    tipo:'Estágio', area:'Marketing Digital',        skills:['Marketing Digital','SEO','Copywriting'],              descricao:'Auxílio na criação de conteúdo para redes sociais, gestão de campanhas Google Ads e análise de métricas de marketing digital.',                                          requisitos:['Cursando Marketing, Comunicação ou afins','Canva básico','Boa escrita'], beneficios:['Bolsa R$ 1.200','Vale Transporte','Flexibilidade de horário'] },
  { id:3,  cargo:'Desenvolvedor Front-End Jr',    empresa:'TechSoft Sistemas',        cidade:'Curitiba - PR',     modalidade:'Presencial', tipo:'CLT',    area:'Tecnologia da Informação', skills:['HTML/CSS','JavaScript','React','Git'],                descricao:'Desenvolvimento de interfaces web modernas e responsivas usando React e boas práticas de acessibilidade. Participação em code reviews.',                                  requisitos:['React.js','HTML/CSS avançado','Git','Inglês Técnico'], beneficios:['Plano de Saúde','VR R$50/dia','Gympass','13° Salário'] },
  { id:4,  cargo:'Assistente Administrativo',     empresa:'Grupo Evolução Comercial', cidade:'Belo Horizonte - MG',modalidade:'Presencial',tipo:'CLT',    area:'Administração',            skills:['Excel Avançado','Atendimento ao Cliente','Organização'],descricao:'Apoio administrativo geral, controle de documentos, atendimento a fornecedores e clientes, suporte à equipe gerencial.',                                                    requisitos:['Ensino Médio completo','Excel básico/intermediário','Boa comunicação'], beneficios:['Vale Transporte','Vale Refeição','Plano Odontológico'] },
  { id:5,  cargo:'Técnico de Enfermagem',         empresa:'Hospital São Lucas',       cidade:'Rio de Janeiro - RJ',modalidade:'Presencial',tipo:'CLT',    area:'Saúde',                    skills:['Enfermagem','Biossegurança','Primeiros Socorros'],    descricao:'Assistência direta ao paciente, execução de procedimentos de enfermagem e suporte às equipes médicas nos plantões.',                                                    requisitos:['CTE ativo','Habilitação técnica de enfermagem','Disponibilidade para plantão'], beneficios:['Plano de Saúde','Refeição no Local','Adicional Noturno','Uniforme'] },
  { id:6,  cargo:'Designer UX/UI Jr',             empresa:'Creative Labs Studio',     cidade:'Remoto',            modalidade:'Remoto',    tipo:'PJ',      area:'Design',                   skills:['UX/UI Design','Figma'],                               descricao:'Criação de protótipos interativos, wireframes e interfaces centradas no usuário para aplicativos e web. Participação em design system.',                                 requisitos:['Figma avançado','Portfolio obrigatório','Noções de HTML/CSS'], beneficios:['PJ R$ 4.500/mês','Horário Flexível','Equipamento fornecido'] },
  { id:7,  cargo:'Analista de RH',                empresa:'Conecta Talentos RH',      cidade:'São Paulo - SP',    modalidade:'Híbrido',   tipo:'CLT',     area:'Recursos Humanos',         skills:['Gestão de Pessoas','Psicologia Organizacional'],      descricao:'Recrutamento e seleção, processos de onboarding, treinamentos e desenvolvimento e gestão de clima organizacional.',                                                     requisitos:['Superior em Psicologia ou RH','Excel intermediário','Experiência em R&S'], beneficios:['Plano de Saúde','VA R$ 800/mês','PLR','Horário Flexível'] },
  { id:8,  cargo:'Estágio em Engenharia Civil',   empresa:'Construtora Horizonte',    cidade:'Porto Alegre - RS', modalidade:'Presencial', tipo:'Estágio',area:'Engenharia',               skills:['Excel Avançado','Gestão de Projetos'],                descricao:'Acompanhamento de obras, elaboração de orçamentos, controle de cronogramas e organização da documentação técnica de projetos.',                                          requisitos:['Cursando Eng. Civil (4° ao 8° período)','AutoCAD básico'], beneficios:['Bolsa R$ 1.500','Vale Transporte','Mentoria com Engenheiro Sênior'] },
  { id:9,  cargo:'Trainee Financeiro',            empresa:'FinanceGroup Brasil',      cidade:'Campinas - SP',     modalidade:'Presencial', tipo:'Trainee',area:'Finanças',                 skills:['Gestão Financeira','Excel Avançado','Análise de Dados','SQL'], descricao:'Programa trainee com rotação por áreas de controladoria, tesouraria e planejamento financeiro. Desenvolvimento acelerado.',                               requisitos:['Recém-formado (máx. 2 anos)','Excel avançado','Inglês intermediário'], beneficios:['R$ 4.200','Plano de Saúde','Participação em Resultados','Mentoria Executiva'] },
  { id:10, cargo:'Analista de Logística',         empresa:'LogisBrasil Transportes',  cidade:'Guarulhos - SP',    modalidade:'Presencial', tipo:'CLT',    area:'Logística',                skills:['Logística','Excel Avançado','Planejamento Estratégico'], descricao:'Controle de estoque, roteirização de entregas, gestão de indicadores de desempenho e relacionamento com transportadoras.',                                             requisitos:['Superior em Logística ou Administração','Excel avançado','ERP básico'], beneficios:['VT + VR','Plano de Saúde','Seguro de Vida','PLR'] },
  { id:11, cargo:'Dev Backend Python',            empresa:'InnovateTech Startup',     cidade:'Remoto',            modalidade:'Remoto',    tipo:'CLT',     area:'Tecnologia da Informação', skills:['Python','SQL','Docker','Git'],                         descricao:'Desenvolvimento de APIs e microsserviços em Python com Django e FastAPI. Participação em decisões de arquitetura e infraestrutura.',                                    requisitos:['Python intermediário/avançado','SQL','Git','Inglês Técnico'], beneficios:['Salário até R$ 7.000','100% Remoto','Stock Options','Plano de Saúde'] },
  { id:12, cargo:'Especialista em SEO',           empresa:'MarketUp Digital',         cidade:'Rio de Janeiro - RJ',modalidade:'Híbrido',   tipo:'CLT',    area:'Marketing Digital',        skills:['SEO','Marketing Digital','Copywriting','Análise de Dados'], descricao:'Estratégias de SEO on/off-page, análise de performance, link building e otimização de conteúdo para diferentes segmentos.',                                        requisitos:['Experiência comprovada com SEO','Google Analytics','WordPress'], beneficios:['Plano de Saúde','VA','Cursos Patrocinados','Bônus por Metas'] },
  { id:13, cargo:'Enfermeiro Assistencial',       empresa:'Clínica Bem Estar',        cidade:'Fortaleza - CE',    modalidade:'Presencial', tipo:'CLT',    area:'Saúde',                    skills:['Enfermagem','Liderança','Biossegurança'],             descricao:'Gerenciamento da equipe de técnicos, supervisão de procedimentos clínicos e gestão de qualidade no atendimento ao paciente.',                                         requisitos:['COREN ativo','Experiência hospitalar','Liderança de equipes'], beneficios:['Plano de Saúde Premium','Vale Refeição','Plano Odontológico'] },
  { id:14, cargo:'Analista de Marketing Jr',      empresa:'BrandMasters Comunicação', cidade:'São Paulo - SP',    modalidade:'Híbrido',   tipo:'CLT',     area:'Marketing Digital',        skills:['Marketing Digital','Análise de Dados','Copywriting','SEO'], descricao:'Planejamento e execução de campanhas digitais, análise de métricas e gestão de conteúdo para múltiplos canais.',                                                   requisitos:['Superior em Marketing ou Comunicação','Google Analytics','Redes Sociais'], beneficios:['VR R$ 750','Plano de Saúde','Horário Flexível'] },
  { id:15, cargo:'Assistente de RH',              empresa:'GestãoPro Consultoria',    cidade:'Brasília - DF',     modalidade:'Presencial', tipo:'CLT',    area:'Recursos Humanos',         skills:['Gestão de Pessoas','Atendimento ao Cliente','Excel Avançado'], descricao:'Apoio ao departamento de RH: controle de ponto, benefícios, admissão e demissão, folha de pagamento e arquivos de pessoal.',                                        requisitos:['Cursando ou formado em RH/Psicologia','Excel intermediário','Discrição'], beneficios:['VT + VR','Plano de Saúde','Estabilidade'] },
  { id:16, cargo:'Full Stack Developer Pleno',    empresa:'CloudSolutions Tech',      cidade:'Remoto',            modalidade:'Remoto',    tipo:'PJ',      area:'Tecnologia da Informação', skills:['React','Node.js','SQL','Docker','Git'],               descricao:'Desenvolvimento de aplicações web completas do front ao back, arquitetura de sistemas, code review e mentoria de devs júnior.',                                         requisitos:['React + Node.js','SQL/NoSQL','Docker','Inglês Intermediário'], beneficios:['PJ R$ 9.000–12.000','100% Remoto','Horário Flexível'] },
  { id:17, cargo:'Analista Financeiro Jr',        empresa:'Investia Capital',         cidade:'São Paulo - SP',    modalidade:'Presencial', tipo:'CLT',    area:'Finanças',                 skills:['Gestão Financeira','Excel Avançado','Análise de Dados'], descricao:'Análise de demonstrativos financeiros, elaboração de projeções e relatórios gerenciais para suporte à diretoria.',                                                      requisitos:['Formado em Contábeis/Economia/Administração','Excel Avançado'], beneficios:['Plano de Saúde','PLR','VR/VA','Ambiente Moderno'] },
  { id:18, cargo:'Coordenador de Logística',      empresa:'Express Cargo Logística',  cidade:'Santos - SP',       modalidade:'Presencial', tipo:'CLT',    area:'Logística',                skills:['Logística','Liderança','Planejamento Estratégico','Excel Avançado'], descricao:'Coordenação de operações portuárias, gestão de equipe de 15 colaboradores e controle de indicadores operacionais.',                                             requisitos:['Superior em Logística ou Comércio Exterior','Experiência 3+ anos','Inglês Básico'], beneficios:['Salário até R$ 6.500','Plano de Saúde','PLR','VR/VA'] }
];
